name: npx tests
on: [push]
jobs:
  npx-tests:
    name: ${{ matrix.os }} node@${{ matrix.node-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        npx-version: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install -g npx@${{ matrix.npx-version }}
    - run: npm --version
    - run: npx https://github.com/rwoll/where-am-i-executing.git
